// The NexTradePro coin universe — the seed list of assets the Market Data
// Service tracks. This is metadata only (symbol, name, category tags, links);
// all live values (price, market cap, volume, supply, rank) are filled in and
// kept fresh by the sync job. The DB is the source of truth at runtime — this
// list only bootstraps it and adds any new listings.
//
// Categories: LAYER1, LAYER2, DEFI, MEME, AI, GAMING, METAVERSE, STABLECOIN,
// INFRA, EXCHANGE, PRIVACY, RWA. (Trending / gainers / losers are dynamic.)

export interface CoinSeed {
  symbol: string; // BTC
  name: string;
  pair?: string; // exchange pair; defaults to `${symbol}USDT`
  categories: string[];
  website?: string;
  explorer?: string;
  whitepaper?: string;
}

export const COIN_UNIVERSE: CoinSeed[] = [
  { symbol: 'BTC', name: 'Bitcoin', categories: ['LAYER1'], website: 'https://bitcoin.org', explorer: 'https://blockchain.com/explorer', whitepaper: 'https://bitcoin.org/bitcoin.pdf' },
  { symbol: 'ETH', name: 'Ethereum', categories: ['LAYER1', 'DEFI'], website: 'https://ethereum.org', explorer: 'https://etherscan.io' },
  { symbol: 'BNB', name: 'BNB', categories: ['LAYER1', 'EXCHANGE'], website: 'https://bnbchain.org', explorer: 'https://bscscan.com' },
  { symbol: 'SOL', name: 'Solana', categories: ['LAYER1'], website: 'https://solana.com', explorer: 'https://solscan.io' },
  { symbol: 'XRP', name: 'XRP', categories: ['LAYER1', 'INFRA'], website: 'https://ripple.com', explorer: 'https://xrpscan.com' },
  { symbol: 'ADA', name: 'Cardano', categories: ['LAYER1'], website: 'https://cardano.org', explorer: 'https://cardanoscan.io' },
  { symbol: 'DOGE', name: 'Dogecoin', categories: ['MEME'], website: 'https://dogecoin.com' },
  { symbol: 'AVAX', name: 'Avalanche', categories: ['LAYER1'], website: 'https://avax.network', explorer: 'https://snowtrace.io' },
  { symbol: 'TRX', name: 'TRON', categories: ['LAYER1'], website: 'https://tron.network', explorer: 'https://tronscan.org' },
  { symbol: 'LINK', name: 'Chainlink', categories: ['INFRA', 'DEFI'], website: 'https://chain.link' },
  { symbol: 'DOT', name: 'Polkadot', categories: ['LAYER1', 'INFRA'], website: 'https://polkadot.network' },
  { symbol: 'MATIC', name: 'Polygon', categories: ['LAYER2'], website: 'https://polygon.technology', explorer: 'https://polygonscan.com' },
  { symbol: 'TON', name: 'Toncoin', categories: ['LAYER1'], website: 'https://ton.org' },
  { symbol: 'SHIB', name: 'Shiba Inu', categories: ['MEME'], website: 'https://shibatoken.com' },
  { symbol: 'LTC', name: 'Litecoin', categories: ['LAYER1'], website: 'https://litecoin.org', explorer: 'https://blockchair.com/litecoin' },
  { symbol: 'BCH', name: 'Bitcoin Cash', categories: ['LAYER1'], website: 'https://bitcoincash.org' },
  { symbol: 'UNI', name: 'Uniswap', categories: ['DEFI'], website: 'https://uniswap.org' },
  { symbol: 'DAI', name: 'Dai', categories: ['STABLECOIN', 'DEFI'], website: 'https://makerdao.com' },
  { symbol: 'ATOM', name: 'Cosmos', categories: ['LAYER1', 'INFRA'], website: 'https://cosmos.network' },
  { symbol: 'XLM', name: 'Stellar', categories: ['LAYER1', 'INFRA'], website: 'https://stellar.org' },
  { symbol: 'ETC', name: 'Ethereum Classic', categories: ['LAYER1'], website: 'https://ethereumclassic.org' },
  { symbol: 'FIL', name: 'Filecoin', categories: ['INFRA'], website: 'https://filecoin.io' },
  { symbol: 'APT', name: 'Aptos', categories: ['LAYER1'], website: 'https://aptosfoundation.org' },
  { symbol: 'NEAR', name: 'NEAR Protocol', categories: ['LAYER1', 'AI'], website: 'https://near.org' },
  { symbol: 'ICP', name: 'Internet Computer', categories: ['LAYER1', 'INFRA'], website: 'https://internetcomputer.org' },
  { symbol: 'HBAR', name: 'Hedera', categories: ['LAYER1', 'INFRA'], website: 'https://hedera.com' },
  { symbol: 'ARB', name: 'Arbitrum', categories: ['LAYER2'], website: 'https://arbitrum.io' },
  { symbol: 'OP', name: 'Optimism', categories: ['LAYER2'], website: 'https://optimism.io' },
  { symbol: 'VET', name: 'VeChain', categories: ['INFRA', 'RWA'], website: 'https://vechain.org' },
  { symbol: 'MKR', name: 'Maker', categories: ['DEFI'], website: 'https://makerdao.com' },
  { symbol: 'INJ', name: 'Injective', categories: ['DEFI', 'LAYER1'], website: 'https://injective.com' },
  { symbol: 'AAVE', name: 'Aave', categories: ['DEFI'], website: 'https://aave.com' },
  { symbol: 'GRT', name: 'The Graph', categories: ['INFRA', 'AI'], website: 'https://thegraph.com' },
  { symbol: 'RNDR', name: 'Render', categories: ['AI', 'INFRA'], website: 'https://rendernetwork.com' },
  { symbol: 'ALGO', name: 'Algorand', categories: ['LAYER1'], website: 'https://algorand.com' },
  { symbol: 'STX', name: 'Stacks', categories: ['LAYER2'], website: 'https://stacks.co' },
  { symbol: 'IMX', name: 'Immutable', categories: ['LAYER2', 'GAMING'], website: 'https://immutable.com' },
  { symbol: 'FTM', name: 'Fantom', categories: ['LAYER1'], website: 'https://fantom.foundation' },
  { symbol: 'THETA', name: 'Theta Network', categories: ['INFRA'], website: 'https://thetatoken.org' },
  { symbol: 'SAND', name: 'The Sandbox', categories: ['METAVERSE', 'GAMING'], website: 'https://sandbox.game' },
  { symbol: 'MANA', name: 'Decentraland', categories: ['METAVERSE', 'GAMING'], website: 'https://decentraland.org' },
  { symbol: 'AXS', name: 'Axie Infinity', categories: ['GAMING', 'METAVERSE'], website: 'https://axieinfinity.com' },
  { symbol: 'FLOW', name: 'Flow', categories: ['LAYER1', 'GAMING'], website: 'https://flow.com' },
  { symbol: 'EGLD', name: 'MultiversX', categories: ['LAYER1'], website: 'https://multiversx.com' },
  { symbol: 'XTZ', name: 'Tezos', categories: ['LAYER1'], website: 'https://tezos.com' },
  { symbol: 'CHZ', name: 'Chiliz', categories: ['GAMING'], website: 'https://chiliz.com' },
  { symbol: 'EOS', name: 'EOS', categories: ['LAYER1'], website: 'https://eosnetwork.com' },
  { symbol: 'CAKE', name: 'PancakeSwap', categories: ['DEFI'], website: 'https://pancakeswap.finance' },
  { symbol: 'SNX', name: 'Synthetix', categories: ['DEFI'], website: 'https://synthetix.io' },
  { symbol: 'CRV', name: 'Curve DAO', categories: ['DEFI'], website: 'https://curve.fi' },
  { symbol: 'LDO', name: 'Lido DAO', categories: ['DEFI'], website: 'https://lido.fi' },
  { symbol: 'FET', name: 'Fetch.ai', categories: ['AI'], website: 'https://fetch.ai' },
  { symbol: 'AGIX', name: 'SingularityNET', categories: ['AI'], website: 'https://singularitynet.io' },
  { symbol: 'OCEAN', name: 'Ocean Protocol', categories: ['AI', 'DEFI'], website: 'https://oceanprotocol.com' },
  { symbol: 'TAO', name: 'Bittensor', categories: ['AI'], website: 'https://bittensor.com' },
  { symbol: 'WLD', name: 'Worldcoin', categories: ['AI'], website: 'https://worldcoin.org' },
  { symbol: 'PEPE', name: 'Pepe', categories: ['MEME'], website: 'https://pepe.vip' },
  { symbol: 'WIF', name: 'dogwifhat', categories: ['MEME'], website: 'https://dogwifcoin.org' },
  { symbol: 'FLOKI', name: 'Floki', categories: ['MEME'], website: 'https://floki.com' },
  { symbol: 'BONK', name: 'Bonk', categories: ['MEME'], website: 'https://bonkcoin.com' },
  { symbol: 'USDC', name: 'USD Coin', categories: ['STABLECOIN'], website: 'https://circle.com' },
  { symbol: 'USDT', name: 'Tether', categories: ['STABLECOIN'], website: 'https://tether.to' },
  { symbol: 'TUSD', name: 'TrueUSD', categories: ['STABLECOIN'], website: 'https://tusd.io' },
  { symbol: 'FDUSD', name: 'First Digital USD', categories: ['STABLECOIN'] },
  { symbol: 'RUNE', name: 'THORChain', categories: ['DEFI', 'INFRA'], website: 'https://thorchain.org' },
  { symbol: 'SUI', name: 'Sui', categories: ['LAYER1'], website: 'https://sui.io' },
  { symbol: 'SEI', name: 'Sei', categories: ['LAYER1'], website: 'https://sei.io' },
  { symbol: 'TIA', name: 'Celestia', categories: ['INFRA', 'LAYER1'], website: 'https://celestia.org' },
  { symbol: 'PYTH', name: 'Pyth Network', categories: ['INFRA', 'DEFI'], website: 'https://pyth.network' },
  { symbol: 'JUP', name: 'Jupiter', categories: ['DEFI'], website: 'https://jup.ag' },
  { symbol: 'JTO', name: 'Jito', categories: ['DEFI'], website: 'https://jito.network' },
  { symbol: 'ONDO', name: 'Ondo', categories: ['RWA', 'DEFI'], website: 'https://ondo.finance' },
  { symbol: 'ENA', name: 'Ethena', categories: ['DEFI', 'STABLECOIN'], website: 'https://ethena.fi' },
  { symbol: 'STRK', name: 'Starknet', categories: ['LAYER2'], website: 'https://starknet.io' },
  { symbol: 'MANTA', name: 'Manta Network', categories: ['LAYER2', 'PRIVACY'], website: 'https://manta.network' },
  { symbol: 'DYDX', name: 'dYdX', categories: ['DEFI'], website: 'https://dydx.exchange' },
  { symbol: 'GMX', name: 'GMX', categories: ['DEFI'], website: 'https://gmx.io' },
  { symbol: 'ZEC', name: 'Zcash', categories: ['PRIVACY'], website: 'https://z.cash' },
  { symbol: 'XMR', name: 'Monero', categories: ['PRIVACY'], website: 'https://getmonero.org' },
  { symbol: 'DASH', name: 'Dash', categories: ['PRIVACY'], website: 'https://dash.org' },
  { symbol: 'ROSE', name: 'Oasis Network', categories: ['PRIVACY', 'LAYER1'], website: 'https://oasis.net' },
  { symbol: 'SCRT', name: 'Secret', categories: ['PRIVACY', 'LAYER1'], website: 'https://scrt.network' },
  { symbol: 'KAVA', name: 'Kava', categories: ['DEFI', 'LAYER1'], website: 'https://kava.io' },
  { symbol: 'COMP', name: 'Compound', categories: ['DEFI'], website: 'https://compound.finance' },
  { symbol: 'ZRX', name: '0x Protocol', categories: ['DEFI', 'INFRA'], website: 'https://0x.org' },
  { symbol: '1INCH', name: '1inch', categories: ['DEFI'], website: 'https://1inch.io' },
  { symbol: 'SUSHI', name: 'SushiSwap', categories: ['DEFI'], website: 'https://sushi.com' },
  { symbol: 'YFI', name: 'yearn.finance', categories: ['DEFI'], website: 'https://yearn.fi' },
  { symbol: 'BAL', name: 'Balancer', categories: ['DEFI'], website: 'https://balancer.fi' },
  { symbol: 'ENS', name: 'Ethereum Name Service', categories: ['INFRA'], website: 'https://ens.domains' },
  { symbol: 'LRC', name: 'Loopring', categories: ['LAYER2'], website: 'https://loopring.org' },
  { symbol: 'GALA', name: 'Gala', categories: ['GAMING'], website: 'https://gala.com' },
  { symbol: 'ENJ', name: 'Enjin Coin', categories: ['GAMING', 'METAVERSE'], website: 'https://enjin.io' },
  { symbol: 'APE', name: 'ApeCoin', categories: ['METAVERSE', 'GAMING'], website: 'https://apecoin.com' },
  { symbol: 'PORTAL', name: 'Portal', categories: ['GAMING'], website: 'https://portalgaming.com' },
  { symbol: 'PIXEL', name: 'Pixels', categories: ['GAMING'], website: 'https://pixels.xyz' },
  { symbol: 'BEAM', name: 'Beam', categories: ['GAMING'], website: 'https://onbeam.com' },
  { symbol: 'ILV', name: 'Illuvium', categories: ['GAMING', 'METAVERSE'], website: 'https://illuvium.io' },
  { symbol: 'GMT', name: 'STEPN', categories: ['GAMING'], website: 'https://stepn.com' },
  { symbol: 'MINA', name: 'Mina', categories: ['LAYER1', 'PRIVACY'], website: 'https://minaprotocol.com' },
  { symbol: 'KSM', name: 'Kusama', categories: ['LAYER1', 'INFRA'], website: 'https://kusama.network' },
  { symbol: 'ZIL', name: 'Zilliqa', categories: ['LAYER1'], website: 'https://zilliqa.com' },
  { symbol: 'WAVES', name: 'Waves', categories: ['LAYER1'], website: 'https://waves.tech' },
  { symbol: 'QNT', name: 'Quant', categories: ['INFRA', 'RWA'], website: 'https://quant.network' },
  { symbol: 'NEO', name: 'Neo', categories: ['LAYER1'], website: 'https://neo.org' },
  { symbol: 'IOTA', name: 'IOTA', categories: ['INFRA', 'RWA'], website: 'https://iota.org' },
  { symbol: 'XEC', name: 'eCash', categories: ['LAYER1'], website: 'https://e.cash' },
  { symbol: 'CFX', name: 'Conflux', categories: ['LAYER1'], website: 'https://confluxnetwork.org' },
  { symbol: 'KDA', name: 'Kadena', categories: ['LAYER1'], website: 'https://kadena.io' },
  { symbol: 'CELO', name: 'Celo', categories: ['LAYER1', 'RWA'], website: 'https://celo.org' },
  { symbol: 'AR', name: 'Arweave', categories: ['INFRA'], website: 'https://arweave.org' },
  { symbol: 'HNT', name: 'Helium', categories: ['INFRA'], website: 'https://helium.com' },
  { symbol: 'AKT', name: 'Akash Network', categories: ['AI', 'INFRA'], website: 'https://akash.network' },
  { symbol: 'IOTX', name: 'IoTeX', categories: ['INFRA', 'RWA'], website: 'https://iotex.io' },
  { symbol: 'ANKR', name: 'Ankr', categories: ['INFRA'], website: 'https://ankr.com' },
  { symbol: 'SKL', name: 'SKALE', categories: ['LAYER2', 'INFRA'], website: 'https://skale.space' },
  { symbol: 'CKB', name: 'Nervos Network', categories: ['LAYER1'], website: 'https://nervos.org' },
  { symbol: 'ONE', name: 'Harmony', categories: ['LAYER1'], website: 'https://harmony.one' },
  { symbol: 'ZEN', name: 'Horizen', categories: ['PRIVACY'], website: 'https://horizen.io' },
  { symbol: 'DCR', name: 'Decred', categories: ['LAYER1', 'PRIVACY'], website: 'https://decred.org' },
  { symbol: 'RVN', name: 'Ravencoin', categories: ['LAYER1'], website: 'https://ravencoin.org' },
  { symbol: 'ICX', name: 'ICON', categories: ['LAYER1'], website: 'https://icon.community' },
  { symbol: 'ONT', name: 'Ontology', categories: ['LAYER1'], website: 'https://ont.io' },
  { symbol: 'QTUM', name: 'Qtum', categories: ['LAYER1'], website: 'https://qtum.org' },
  { symbol: 'SC', name: 'Siacoin', categories: ['INFRA'], website: 'https://sia.tech' },
  { symbol: 'STORJ', name: 'Storj', categories: ['INFRA'], website: 'https://storj.io' },
  { symbol: 'BAND', name: 'Band Protocol', categories: ['INFRA', 'DEFI'], website: 'https://bandprotocol.com' },
  { symbol: 'API3', name: 'API3', categories: ['INFRA', 'DEFI'], website: 'https://api3.org' },
  { symbol: 'UMA', name: 'UMA', categories: ['DEFI'], website: 'https://uma.xyz' },
  { symbol: 'DODO', name: 'DODO', categories: ['DEFI'], website: 'https://dodoex.io' },
  { symbol: 'PENDLE', name: 'Pendle', categories: ['DEFI'], website: 'https://pendle.finance' },
  { symbol: 'RPL', name: 'Rocket Pool', categories: ['DEFI'], website: 'https://rocketpool.net' },
  { symbol: 'FXS', name: 'Frax Share', categories: ['DEFI', 'STABLECOIN'], website: 'https://frax.finance' },
  { symbol: 'CVX', name: 'Convex Finance', categories: ['DEFI'], website: 'https://convexfinance.com' },
  { symbol: 'SSV', name: 'ssv.network', categories: ['INFRA', 'DEFI'], website: 'https://ssv.network' },
  { symbol: 'METIS', name: 'Metis', categories: ['LAYER2'], website: 'https://metis.io' },
  { symbol: 'BLUR', name: 'Blur', categories: ['DEFI'], website: 'https://blur.io' },
  { symbol: 'MASK', name: 'Mask Network', categories: ['INFRA', 'PRIVACY'], website: 'https://mask.io' },
  { symbol: 'AUDIO', name: 'Audius', categories: ['INFRA'], website: 'https://audius.co' },
  { symbol: 'C98', name: 'Coin98', categories: ['DEFI'], website: 'https://coin98.com' },
  { symbol: 'WOO', name: 'WOO Network', categories: ['DEFI', 'EXCHANGE'], website: 'https://woo.org' },
  { symbol: 'KNC', name: 'Kyber Network', categories: ['DEFI'], website: 'https://kyber.network' },
  { symbol: 'OKB', name: 'OKB', categories: ['EXCHANGE'], website: 'https://okx.com' },
  { symbol: 'CRO', name: 'Cronos', categories: ['EXCHANGE', 'LAYER1'], website: 'https://cronos.org' },
  { symbol: 'KCS', name: 'KuCoin Token', categories: ['EXCHANGE'], website: 'https://kucoin.com' },
  { symbol: 'GT', name: 'GateToken', categories: ['EXCHANGE'], website: 'https://gate.io' },
  { symbol: 'BGB', name: 'Bitget Token', categories: ['EXCHANGE'], website: 'https://bitget.com' },
  { symbol: 'MX', name: 'MX Token', categories: ['EXCHANGE'], website: 'https://mexc.com' },
  { symbol: 'JASMY', name: 'JasmyCoin', categories: ['INFRA', 'RWA'], website: 'https://jasmy.co.jp' },
  { symbol: 'POLYX', name: 'Polymesh', categories: ['RWA'], website: 'https://polymesh.network' },
  { symbol: 'PENGU', name: 'Pudgy Penguins', categories: ['MEME'], website: 'https://pudgypenguins.com' },
  { symbol: 'MEW', name: 'cat in a dogs world', categories: ['MEME'] },
  { symbol: 'BRETT', name: 'Brett', categories: ['MEME'] },
  { symbol: 'TURBO', name: 'Turbo', categories: ['MEME', 'AI'] },
  { symbol: 'W', name: 'Wormhole', categories: ['INFRA'], website: 'https://wormhole.com' },
  { symbol: 'ZK', name: 'ZKsync', categories: ['LAYER2'], website: 'https://zksync.io' },
  { symbol: 'BLAST', name: 'Blast', categories: ['LAYER2'], website: 'https://blast.io' },
  { symbol: 'DYM', name: 'Dymension', categories: ['INFRA', 'LAYER1'], website: 'https://dymension.xyz' },
  { symbol: 'ALT', name: 'AltLayer', categories: ['INFRA', 'LAYER2'], website: 'https://altlayer.io' },
  { symbol: 'SAGA', name: 'Saga', categories: ['INFRA', 'LAYER1'], website: 'https://saga.xyz' },
  { symbol: 'OM', name: 'MANTRA', categories: ['RWA'], website: 'https://mantrachain.io' },
  { symbol: 'ATH', name: 'Aethir', categories: ['AI', 'INFRA'], website: 'https://aethir.com' },
  { symbol: 'IO', name: 'io.net', categories: ['AI', 'INFRA'], website: 'https://io.net' },
  { symbol: 'ARKM', name: 'Arkham', categories: ['AI', 'INFRA'], website: 'https://arkm.com' },
  { symbol: 'NMR', name: 'Numeraire', categories: ['AI', 'DEFI'], website: 'https://numer.ai' },
  { symbol: 'CTXC', name: 'Cortex', categories: ['AI'], website: 'https://cortexlabs.ai' },
  { symbol: 'PHB', name: 'Phoenix', categories: ['AI'], website: 'https://phoenix.global' },
  { symbol: 'VANRY', name: 'Vanar Chain', categories: ['AI', 'GAMING'], website: 'https://vanarchain.com' },
  { symbol: 'AIOZ', name: 'AIOZ Network', categories: ['AI', 'INFRA'], website: 'https://aioz.network' },
];
